<?php
/*
namespace Hiberus\Ruizalejos\Console;

use Hiberus\Ruizalejos\Model\Examen;
use Hiberus\Ruizalejos\Block\Index;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class RuizalejosCommand extends Command
{

    /**
     * @var Examen
     */
   /* protected Examen $examen;

    /**
     * @var Index
     */
   /* protected Index $index;

    /**
     * @param Index $index;
     */
   /* public function __construct(Index $index,Examen $examen)
    {
        $this->index = $index;
        $this->examen = $examen;
        parent::__construct();

    }

    protected function configure()
    {
        $this->setName('hiberus:ruizalejos')->setDescription('Mostrar datos');
        parent::configure(); // TODO: Change the autogenerated stub
    }

    /**
     * @param InputInterface $input
     * @param OutputInterface $output
     * @return int|void
     */
   /* protected function execute(InputInterface $input, OutputInterface $output)
    {
        $alumnos = $this->index->getAlumno();
        foreach ($alumnos as $al) {
            $this->examen->setIdExam($al->getIdExam());
            $this->examen->setFirstName($al->getFirstName());
            $this->examen->setLastName($al->getLastName());
            $this->examen->setMark($al->getMark());
            $output->writeln('<info> Nombre ' . $this->examen->getFirstname() . 'Apellido' . $this->examen->getLastname() . 'Nota' . $this->examen->getMark() .'</info>');
        }


    }
}
*/
