<?php
/**
 * @var \Hiberus\Ruizalejos\Block\Index $block
 */
$alumnos=$block->getAlumno();
$suma=0;
$max1=0;
$max2=0;
$max3=0;

$i=0;
$notaMin = $block->getNota();
$elem = $block->getElements();
?>
<h2 class="title">Students' List</h2>
<?php
    foreach($alumnos as $al) {
        //en este if calculo las 3 maximas notas
        if ($al->getMark() > $max1) {
            $max2 = $max1;
            $max1 = $al->getMark();
        } else {
            if ($al->getMark() > $max2) {
                $max3 = $max2;
                $max2 = $al->getMark();
            } else {
                if ($al->getMark() > $max3) {
                    $max3 = $al->getMark();
                }
            }
        }
        //if ($i++ == $elem) break;
    }



    foreach( $alumnos as $alu) {
        if($alu->getMark() == $max1 || $alu->getMark() == $max2 ||  $alu->getMark() == $max3 ) {
        ?>
            <ul class="<?php if($alu->getMark()<$notaMin){ ?> susptop <?php } else { ?> aprobtop <?php }?>top">
        <?php } else {?>
            <ul class="<?php if($alu->getMark()<$notaMin){ ?> suspendido <?php } else { ?> aprobado <?php }?>">
                <?php } ?>
                <li>Name: <?= $alu->getFirstName();?></li>
                <li>Surname: <?= $alu->getLastName();?></li>
                <li>Mark <?= $alu->getMark();?></li>
            </ul>
<?php $suma+=$alu->getMark();
        //if ($i++ == $elem) break;
}
?>
<p>Average of Marks <?= $suma/(count($alumnos)) ?></p>
<p>Total number of students: <?= (count($alumnos)) ?></p>
<p><?=$max1 ?></p>
<p><?=$max2 ?></p>
<p><?=$max3 ?></p>

