<?php
/**
 * @var \Hiberus\Ruizalejos\Block\Index $block
 */
$alumnos=$block->getAlumno();
$suma=0;
?>
<h2 class="title">Students' List</h2>
<?php
    foreach($alumnos as $al){ ?>

<ul class="<?php if($al->getMark()<5){ ?> suspendido <?php } else { ?> aprobado <?php }?>">
    <li>Name: <?= $al->getFirstName();?></li>
    <li>Surname: <?= $al->getLastName();?></li>
    <li>Mark <?= $al->getMark();?></li>

</ul>
<?php $suma+=$al->getMark(); } ?>
<p>Average of Marks <?= $suma/(count($alumnos)) ?></p>
<p>Total number of students: <?= (count($alumnos)) ?></p>
