<?php
/**
 * @var \Hiberus\Ruizalejos\Block\Index $block
 */
$alumnos=$block->getAlumno();

$suma=0;
$max1=0;
$max2=0;
$max3=0;

$i=0;
$notaMin = $block->getNota();
$elem = $block->getElements();
?>

<!--Script que calcula las 3 mejores notas de la clase -->
<?php
     foreach($alumnos as $al) {
        //en este if calculo las 3 maximas notas
        if ($al->getMark() > $max1) {
            $max2 = $max1;
            $max1 = $al->getMark();
        } else {
            if ($al->getMark() > $max2) {
                $max3 = $max2;
                $max2 = $al->getMark();
            } else {
                if ($al->getMark() > $max3) {
                    $max3 = $al->getMark();
                }
            }
        }
        //if ($i++ == $elem) break;
    }
?>

<h2 class="title">Students' List</h2>

<?php
    foreach( $alumnos as $alu) {
        //si es una de las 3 maximas notas
        if($alu->getMark() == $max1 || $alu->getMark() == $max2 ||  $alu->getMark() == $max3 ) {
        ?>
            <!-- clase especial para las 3 mejores notas -->
            <ul class="<?php if($alu->getMark()<$notaMin){ ?> susptop <?php } else { ?> aprobtop <?php }?>top">
        <?php } else {?>
            <!-- clase normal para el resto que no tengan las 3 mejores notas -->
            <ul class="<?php if($alu->getMark()<$notaMin){ ?> suspendido <?php } else { ?> aprobado <?php }?>">
                <?php } ?>
                <li>Name: <?= $alu->getFirstName();?></li>
                <li>Surname: <?= $alu->getLastName();?></li>
                <li>Mark <?= $alu->getMark();?></li>
            </ul>
            
        <!--En este trozo calculo la suma -->   
        <?php $suma+=$alu->getMark();
                //if ($i++ == $elem) break;
        } ?>
        
        <!--Obtengo la media -->
        <p>Average of Marks <?= $suma/(count($alumnos)) ?></p>
        <p>Total number of students: <?= (count($alumnos)) ?></p>
        <button id="notaAlta">Mostrar la nota mas alta</button>
        <p><?=$max1 ?></p>
        <p><?=$max2 ?></p>
        <p><?=$max3 ?></p>


<script>
    var max1= <?= $max1?>
</script>
<script>
    require(['jquery', 'notaAlta'], function($, notaAlta) {
        notaAlta('#notaAlta');
    });
</script>

